import Head from "next/head";
import HomePage from "./components/Home";
import CollectionPage from "./components/Studio";
import Demonstrations from "./components/Demonstration";
import ProductCard from "./components/ProductCard";
import AtmosphereDesc from "./components/AtmosphereDesc";
import DemonstrationAtmosphere from "./components/DiscoverAtmosphere";
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
        <HomePage/>
        <Demonstrations/>
        <ProductCard/>
        <CollectionPage/>
        <ProductCard visibleFooter={true }/>
        <AtmosphereDesc/>
        <DemonstrationAtmosphere/>
    </>
  );
}
