import React from 'react';
import Head from 'next/head';
import HomePage from './home';
import PropTypes from 'prop-types';

export default function Main({ textConstants }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <HomePage homePage={textConstants.homePage} />
    </>
  );
}

Main.propTypes = {
  textConstants: PropTypes.shape({
    homePage: PropTypes.object.isRequired,
  }).isRequired,
};
